### ISSUE TITLE
Error: `TypeError: Cannot read property 'length' of undefined`

### ISSUE THREAD

**Issue by starhoshi** [1amageek/pring.ts#22]
## Error

```
   TypeError: Cannot read property 'length' of undefined
       at User.Base.init (/user_code/node_modules/pring/src/pring.js:145:78)
       at Function.<anonymous> (/user_code/node_modules/pring/src/pring.js:106:40)
       at step (/user_code/node_modules/pring/src/pring.js:42:23)
       at Object.next (/user_code/node_modules/pring/src/pring.js:23:53)
       at fulfilled (/user_code/node_modules/pring/src/pring.js:14:58)
       at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

## Code

```ts
export class User extends Pring.Base { }

const user = <User>await Model.User.get(user.id) // error!
```

An error occurs because the User property count is zero.

**Comment by 1amageek** [comment]
Fixed
